# -*- coding: utf-8 -*-
"""2311cs020531.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EGsny2wjWYs4R52LCvf_aaajjTPgybJs
"""

import pandas as pd

screen_time = [2, 4, 8, 9, 10]
sleep_hours = [3, 4, 6, 7, 9]
stu_name = ["Tejaswi", "Abhi", "Karthik", "Raj", "Sita"]

dict1 = {
    "screen_time": screen_time,
    "sleep_hours": sleep_hours,
    "stu_name": stu_name
}

print(dict1)
df = pd.DataFrame(dict1)
print(df)